spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./test01;AUTO_SERVER=TRUE

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true 
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
